version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/packages/mrml-cli"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/packages/mrml-core"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/packages/mrml-wasm"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/mrml-wasm/examples/browser"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/mrml-wasm/examples/node"
    schedule:
      interval: "weekly"
