name: mrml-core release

on:
  workflow_call:
    inputs:
      release_tag:
        description: "Release tag to use"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to use"
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: notify mastodon
        uses: cbrgm/mastodon-github-action@v2
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          language: "en" # ISO 639 language code for the toot.
          message: |
            👋 Hey! I just released a new version of mrml! 🦀
            https://github.com/jdrouet/mrml/releases/tag/${{ inputs.release_tag }} and https://crates.io/crates/mrml
          url: ${{ secrets.MASTODON_URL }}
          visibility: "public"
        continue-on-error: true
